package-lock.json
package.json
src/frontend/assembly.ts
src/frontend/body.ts
src/frontend/checker.ts
src/frontend/checker_relations.ts
src/frontend/parser.ts
test/parser/literals/stringof.test.js
test/parser/parse_nf.ts
test/typecheck/literals/stringof.test.js
test/typecheck/typecheck_nf.ts

Parser and checker support for StringOf and CStringOf literals + validator declarations.
Can now write code like the following:
```
validator NumberRE = /[0-9]+/; 
function fok(): StringOf<NumberRE> { 
return "123"_NumberRE; //ok validates with regex at compile time
}
function ferr(): StringOf<NumberRE> { 
return ""_NumberRE; //fails regex => compiler error 
}
```
The Regex language that can be used for these validators is the [BREX Structured Text Processing format](https://github.com/BosqueLanguage/BREX).

StringOf and CStringOf Support

---

src/frontend/assembly.ts
src/frontend/checker.ts
src/frontend/checker_relations.ts
src/frontend/parser.ts
src/frontend/parser_env.ts
src/frontend/type.ts
test/parser/access_exps/ns_scope.test.js
test/parser/parse_nf.ts

Now imports are enforced:
```
NSOther::Foo
```
is now an error -- requires a using
```
declare namespace Main {
using NSOther;
}
```
or
```
declare namespace Main {
using ReallyLong::Scoped::Namespace as NSOther;
}
```

Enforce Scope imports and Round-trip Namespace Scoping

---

package-lock.json
package.json
src/backend/jsemitter.ts
src/backend/runtime/runtime.mjs
src/frontend/assembly.ts
src/frontend/body.ts
src/frontend/checker.ts
src/frontend/parser.ts
test/runtime/cons_exps/cons_type.test.js
test/typecheck/type/stringish_no_ops.test.js

Updated Brex library support for consistent use between compile/runtime
1. Named regex works at runtime
2. CRegex now supported
Updated Namespace scoping to fix bugs
- Only implicit lookups for top-level namespace name (not full prefixes so sub-namespaces must scope from top-level)
- Tidy up import setup and make notes about extending for package/module scoping as well

Update to Brex lib + scope resolution

---

src/frontend/parser.ts
src/frontend/parser_kw.ts
test/parser/bin_exps/division.test.js

Using BREX with JS call bindings was slower than desired (not sure if it was repeated string serialization, cross language calls, or BREX matching is still un-optimized). However, with the number of calls it added up and was really hitting CI type runs. 
New code just uses JS regexes whenever possible.

Lexer speedup

---

src/core/list.bsq
src/core/xcore_list_exec.bsq
src/core/xcore_list_smt.bsq
src/core/xcore_map_exec.bsq
test/stdlib/list/list_delete.test.js

Helps get closer to closing #75
- Implement very similar logic to how I handled map deletion
- Fix nodes always inserting as black in `insert`, `pushBack`, and `pushFront`
- Ensure RB invariants are maintained through insertion and deletion
- Added some logic to handle case where one sub-tree of root node becomes empty but other is still populated. We now simply move the root node to our non empty sub-tree, without doing so RB properties will get violated. I also added this in our map deletion

List Deletion

---

src/backend/jsemitter/jsemitter.ts
src/backend/jsemitter/runtime/bsqon.mjs
src/backend/smtcore/smtrepr/assembly.bsq
src/backend/smtcore/smtrepr/body.bsq
src/backend/smtcore/transformer/mayerror.bsq
src/backend/smtcore/transformer/smtemitter.bsq
src/backend/smtcore/transformer/smtprocessor.bsq
src/backend/smtcore/transformer/smttransform.bsq
src/bsqir/asm/assembly.bsq
src/bsqir/asm/body.bsq
src/bsqir/simplifier/constsimplify.bsq
src/bsqir/simplifier/explicitify.bsq
src/frontend/bsqir_emit.ts
src/frontend/checker.ts
test/smtoutput/asserts/assert.test.js
test/smtoutput/bin_exps/division.test.js
test/smtoutput/bin_exps/mult.test.js
test/smtoutput/compare_ops/eqop.test.js
test/smtoutput/compare_ops/equality.test.js
test/smtoutput/compare_ops/greater.test.js
test/smtoutput/compare_ops/less.test.js
test/smtoutput/oo_type/entity_simple.test.js
test/smtoutput/smtemit_nf.ts
test/smtoutput/var_decl_assign/single_decls_assign.test.js

A fun little example is below -- can compile to SMTLib and then (1) execute by fixing the inputs or (2) bug find by asserting an error happens and solving for input!
```
declare namespace Main;
entity Foo {
field x: Int;
field y: Int;
}
public function main(f: Foo): Int { 
let k = f.x + f.y;
assert k > f.x;
return k;
}
```

SMT now does at least something interesting

---

build/build_cppemit.js
build/resource_copy.js
src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/cpprepr/cppassembly.bsq
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cppprocessor.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/cmd/analyzecpp.ts
src/cmd/workflows.ts

We are now able to emit very simple functions and variable initialization. I have not overloaded primitive types yet, so some of this code will need to be changed in the future, but I figured it would be good to get a naive approach working first.
As of now we are able to transform a bosque file like so:
```
declare namespace Main;
public function main(): Int {
let xyz: Int = 1i;
return xyz;
}
```
Into:
```
#include "/home/stub/repos/BosqueCore/bin/cppruntime/cppruntime.hpp"
int main() {
int64_t xyz = 1;
return xyz;
}
```

Very Simple C++ Emit

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/cpprepr/cppassembly.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/runtime/emit.cpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cppprocessor.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/cmd/analyzecpp.ts

This adds support for emitting cpp for following operations on Int, Nat, BigInt, BigNat, and Float
- addition
- subtraction
- multiplication
- division
- equality
- non-equality
- less than and less than or equal to
- greater than and greater than or equal to
All of these operations are overloaded in the file `cppruntime.hpp` and all arithmetic is done using `__builtin_*_overflow(...)` . I tried to get any overflow operations to be detected at compile time, but it appears that these builtin overflow arithmetic operations can only detect overflow at runtime, hence throwing `std::runtime_error` whenever overflow is detected _(although I may be wrong here)_. 
I also had to pivot from my user defined literal idea ( instead of emitting `__CoreCpp::Int(1)` we would emit `1_i` where `_i` is …

Binary arithmetic, numeric comparisons, overloaded backend cpp emission

---

package.json
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/runtime/emit.cpp
src/cmd/workflows.ts
test/cppoutput/bin_exps/addition.test.js
test/cppoutput/bin_exps/division.test.js
test/cppoutput/bin_exps/multipication.test.js
test/cppoutput/bin_exps/subtraction.test.js
test/cppoutput/cppemit_nf.ts

We now test cpp emission for:
- addition
- subtraction
- multiplication
- division
Each test also will check for possible overflow cases, ensuring they are detected and handled. These likely aren't 100% coverage, but ensures basic functionality is tested.
Also, our emitted cpp code now writes whatever bosque primitive (for now) is returned from our funny namespaced main (the cpp representation of input bosque code, `__CoreCpp::(type) main() {}`) to cout.

Basic Cpp Emit Testing

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/frontend/bsqir_emit.ts
test/cppoutput/bin_exps/addition.test.js
test/cppoutput/bin_exps/division.test.js
test/cppoutput/bin_exps/multipication.test.js
test/cppoutput/bin_exps/subtraction.test.js
test/cppoutput/compare_ops/equality.test.js
test/cppoutput/compare_ops/greater.test.js
test/cppoutput/compare_ops/less.test.js
test/cppoutput/literals/numeric.test.js
test/cppoutput/literals/special.test.js
test/cppoutput/logical_ops/logical_and.test.js
test/cppoutput/logical_ops/logical_iff.test.js
test/cppoutput/logical_ops/logical_implies.test.js
test/cppoutput/logical_ops/logical_or.test.js
test/cppoutput/logical_ops/op_and.test.js
test/cppoutput/logical_ops/op_or.test.js
test/cppoutput/unary_exps/not.test.js
test/cppoutput/unary_exps/sign.test.js

Cpp emission now supports:
- unary prefix not
- unary prefix negation _(properly, before it was not a defined datatype, just a cstring insertion in the emitted cpp)_
- unary prefix plus
- logical and
- logical or
- logical implies
- logical iff
- logical action and
- logical action or
For example this piece of Bosque code:
```
let neg: Int = -(3i);
let pos: Int = +3i;
let f: Bool = \/(false, false);
let t: Bool = f ==> false;
let tt: Bool = !f;
let ff: Bool = /\(tt, t);
let iff: Bool = true <==> true;
return /\(t, tt, iff); 
```
Emits this cpp:
```
__CoreCpp::Int neg = -3_i;
__CoreCpp::Int pos = +3_i;
bool f = (false || false);
bool t = (!f || false);
bool tt = !f;
bool ff = (tt && t);
bool iff = ((true && true) || (!true && !true));
return (t && tt && iff);
```
Also, logical action …

Cpp Emit Logic Ops, Unary Ops, Logic Action Expressions, & Testing

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/frontend/bsqir_emit.ts
test/cppoutput/if_exp/basic_if.test.js
test/cppoutput/if_stmts/simple_if.test.js
test/cppoutput/if_stmts/simple_ifelse.test.js

We can now emit cpp code for:
- If statements
- If else statements
- If elif else statements
For example, Bosque code like so:
```
if(1n == 2n) { 
return 3i; 
} 
elif(1n == 2n) {
return 2i;
}
elif(3n != 3n) {
return 5i;
}
elif(1i == 1i) {
return 0i;
}
else { 
return 1i;
}
```
Emits in cpp:
```
if((1_n == 2_n)) {
return 3_i;
}
else if((1_n == 2_n)) {
return 2_i;
}
else if((3_n != 3_n)) {
return 5_i;
}
else if((1_i == 1_i)) {
return 0_i;
}
else {
return 1_i;
}
```

Cpp Emit for If Statements

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/cpprepr/cppassembly.bsq
src/backend/cpp/runtime/emit.cpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/bsqir/asm/assembly.bsq
src/bsqir/asm/body.bsq
src/bsqir/simplifier/constsimplify.bsq
src/bsqir/simplifier/explicitify.bsq
src/frontend/bsqir_emit.ts
test/cppoutput/fcall_exps/ns_fcalls.test.js

This adds support for cpp emission of properly nested namespaces, forward declarations, calling namespace functions, function arguments, and resolving named, positional, and default parameters. I also added a context entity to the emitter so we can easily resolve what namespace we are currently in and find functions. And a new field to `AbstractDecl` in bsqir, `fullns: List<CString>` which we use to find namespace function declarations (and more generally just resolving namespaces).
If we have some Bosque code like so:
```
declare namespace Main;
namespace Foo {
function foo(x: Int, y: Int = $x): Int {
return x * y;
}
}
public function main(): Int {
return Foo::foo(10i);
}
```
This emits this cpp:
```
namespace Foo {
__CoreCpp::Int foo(__CoreCpp::Int x, __CoreCpp::Int y); …
```

Cpp Emit Namespace Grouping, Namespace Func Calls, Forward Decls

---

src/frontend/parser.ts
src/frontend/parser_kw.ts
test/parser/access_exps/field_updates.test.js
test/runtime/access_exps/field_updates.test.js
test/typecheck/access_exps/field_updates.test.js

Parse error on `x.f[y=2i]` incorrectly trying to parse as an invoke. Fixed + tests.

Fix update postfix parse bug

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/cpprepr/cppassembly.bsq
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/bsqir/asm/body.bsq
src/frontend/bsqir_emit.ts
test/cppoutput/cons_exps/cons_entity.test.js

We are now able to emit cpp code for simple entities with primitive fields. Constructor w/ default or named parameters and basic field access is supported. They do not emit any type information quite yet (or any methods, although these will be emitted as functions).
Some Bosque code like so:
```
declare namespace Main;
entity Bar {
field x: Int;
field y: Int;
field z: Int;
}
namespace Foo {
function foo(e: Bar): Int {
return e.x + e.y + e.z;
}
}
public function main(): Int {
return Foo::foo( Bar{ 1i, 2i, 3i } );
}
```
Emits:
```
class Bar;
__CoreCpp::Int foo(Bar e);
__CoreCpp::Int main();
class Bar{ 
public:
__CoreCpp::Int x;
__CoreCpp::Int y;
__CoreCpp::Int z;
};
namespace Foo {
__CoreCpp::Int foo(Bar e);
__CoreCpp::Int foo(Bar e) {
return ((e.x + e.y) + e.z);
}
} …
```

Cpp Emit Simple Entity

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/cpprepr/cppassembly.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cppprocessor.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/bsqir/asm/assembly.bsq
src/cmd/analyzecpp.ts
src/frontend/bsqir_emit.ts
test/cppoutput/cppemit_nf.ts
test/cppoutput/mcall_exps/simple_resolved.test.js

We are now able to emit cpp code for static methods and these use a special unicode `this` to avoid any naming conflicts. We also emit the corresponding typeinfo with our entity emission.
For example, this Bosque code:
```
entity Foo { 
field f: Int; 
field o: Int;
method foo(x: Int, y: Int = 1i): Int { 
return this.f + this.o + x + y; 
}
} 
public function main(): Int { 
return Foo{3i, 2i}.foo(3i); 
}
```
Emits:
```
struct Foo;
__CoreCpp::Int main() noexcept;
const __CoreCpp::Int foo(const Foo tᖺis, __CoreCpp::Int x, __CoreCpp::Int y) noexcept;
TypeInfoBase FooType = {
.type_id = 7,
.type_size = 16, 
.slot_size = 2,
.ptr_mask = "00",
.typekey = "Main::Foo"
};
struct Foo{ 
const __CoreCpp::Int f;
const __CoreCpp::Int o;
};
const __CoreCpp::Int foo(const Foo tᖺis, …
```

Cpp Emit Static Methods & TypeInfo

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cppprocessor.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/bsqir/simplifier/constsimplify.bsq
src/bsqir/simplifier/explicitify.bsq
test/cppoutput/fcall_exps/ns_fcalls.test.js
test/cppoutput/if_exp/basic_if.test.js
test/cppoutput/mcall_exps/simple_resolved.test.js
test/cppoutput/special_cons_exps/optional_const.test.js

Added support in explicitify and constsimplify for:
- `DatatypeTypeDecl` and `DatatypeMemberEntityTypeDecl`
- `CallTypeFunctionExpression`
- `IfElifElseStatement`
- `ITestType`
- `BinLogicIFFExpression`
Also deleted default val related code from the cpp emitter as eventually this would be handled in explicitify/constsimplify (and commented out any tests relying on them).

Const Simplify and Explicitify Updates

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/cpprepr/cppassembly.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/runtime/emit.cpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/bsqir/asm/body.bsq
test/cppoutput/asserts/assert.test.js
test/cppoutput/bin_exps/addition.test.js
test/cppoutput/bin_exps/division.test.js
test/cppoutput/bin_exps/multipication.test.js
test/cppoutput/bin_exps/subtraction.test.js
test/cppoutput/compare_ops/equality.test.js

Added support for emitting `enum` and `assert` in cpp. The `assert` is a simple macro that tests whether our condition is false, if so we call `std::longjmp`.
Some bosque code like so
```
enum Foo { f, g } 
public function main(): Bool { 
assert(0i > 0i);
let x = (| 1i, Foo#f |);
return x.1 === Foo#f; 
}
```
Emits in cpp
```
//
// Ref and Tagged Type Forward Declarations
//
}
//
// Value Type Definitions
//
__CoreCpp::TypeInfoBase FooType = {
.type_id = 4,
.type_size = 8, 
.slot_size = 1,
.ptr_mask = "0",
.typekey = "Main::Foo",
.vtable = nullptr
};
enum class Foo {
f,
g
};
//
// Ref and Tagged Type Definitions
//
}
//
// Emitted Functions
//
bool main() noexcept;
bool main() noexcept  {
𝐚𝐬𝐬𝐞𝐫𝐭((0_i > 0_i));
__CoreCpp::Tuple2<1, 1> x = …
```

Cpp Emit Enum Assert

---

src/backend/smtcore/transformer/smttransform.bsq
src/bsqir/simplifier/explicitify.bsq
src/frontend/bsqir_emit.ts
test/smtoutput/cons_exps/cons_cons.test.js
test/smtoutput/cons_exps/cons_entity.test.js
test/smtoutput/fcall_exps/ns_fcalls.test.js
test/smtoutput/mcall_exps/simple_resolved.test.js

Notable:
1. Fix for invoke rcvr -- make sure when calling an method defined on GeneralType (e.g. concept) the rcvr argument is boxed.
2. Fix on binder ifs with datatype -- in special case where there are 2 possibilities then make sure the else case refines down as well as the if case -- e.g. `datatype Foo of F1 {} | F2 {}; ... let x: Foo = ...; if(x)@<F1> then /*$x is F1*/ else /*$x is F2*/; `

Fixes and tests

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/bsqir/simplifier/constsimplify.bsq
src/bsqir/simplifier/explicitify.bsq
src/frontend/bsqir_emit.ts
test/cppoutput/if_exp/basic_if.test.js
test/cppoutput/match_stmts/simple_match.test.js
test/cppoutput/match_stmts/simple_switch.test.js

Added support for cpp emission of `MatchStatement`, `SwitchStatement`, and `IfBinderExpression` . 
Some bosque code like so 
```
public function main(): Int {
let x: Option<Int> = some(3i);
let y: Option<Int> = if(x)@some then some(3i) else none;
match(y)@ {
None => { return 0i; }
| Some<Int> => {
let tmp = $y.value;
switch(tmp) {
3i => { return if(tmp > 2i) then tmp else 0i; }
| _ => { return 0i; }
}
}
}
}
```
Will now emit in cpp
```
__CoreCpp::Int main() noexcept;
__CoreCpp::Int main() noexcept  {
Core::OptionᐸIntᐳ x = Core::OptionᐸIntᐳ{ &Core::SomeᐸIntᐳType, Core::SomeᐸIntᐳ{ 3_i} };
Core::OptionᐸIntᐳ y = ( x.typeinfo != &NoneType 
? ([&]() -> Core::OptionᐸIntᐳ { [[maybe_unused]] __CoreCpp::Int $x = x.access<Core::SomeᐸIntᐳ>().value; return Core::OptionᐸIntᐳ{ …
```

Cpp Emit Match Statement, Switch Statement, and If Binder Expression

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/frontend/bsqir_emit.ts
test/cppoutput/list/list_append.test.js
test/cppoutput/list/list_map.test.js
test/cppoutput/list/list_predof_ops.test.js
test/cppoutput/list/list_reduce.test.js

Added tests for cpp list map, reduce, `pred()` flavours, and append/prepend. 
Also fixed a few varrying bugs that prevented the tests I added from working: 
1. In `bsqir_emit`, `CallTypeFunctionExpression` was not emitting resolved templates (e.g. it was emitting `s_list_mapidx` as `s_list_mapidx<U>` and not something like `s_list_mapidx<Int, Nat>` after resolution)
2. Methods now emit with the type they are declared in as a prefix (something like `FooᘏfooᐸIntᐳ`) to prevent possible naming conflicts
3. `CollectionTypeDecl`s emit before any possible usage now, being emitted grouped with our ref type forward decls
4. `Bool` now emits as a `__CoreCpp::Bool` (which is literally just `typedef bool Bool`) as it makes name type transformation easier

C++ Emit List Tests & Bug Fixes

---

src/backend/cpp/gc/src/language/bsqtype.h
src/backend/cpp/gc/src/runtime/common.h
src/backend/cpp/gc/src/runtime/memory/allocator.h
src/backend/cpp/gc/src/runtime/memory/gc.cpp
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/runtime/makefile
src/backend/cpp/transformer/cppemitter.bsq

This adds support to the GC for our tagged types and support for emission of the call to our gc allocator. I was able to get our emitted nbody to run without issues with these changes.
Now, like how I had in the tests I did have to turn automatic collections off and manually trigger after we exceed our collection threshold as to prevent a collection being triggered mid-allocation. This is something I will have to give some more thought to, but for now these changes should have us in a good spot for moving forward. 
I also had to do some code cleanup here as I found my old code pretty hard to read... should be a bit better now. I'll be doing a bit more cleanup in a future PR to make this easier to read.

GC Tagged Type Support

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/runtime/cppruntime.cpp
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/runtime/makefile
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/backend/jsemitter/jsemitter.ts
src/bsqir/asm/body.bsq
src/bsqir/simplifier/constsimplify.bsq
src/bsqir/simplifier/explicitify.bsq
src/cmd/analyzecpp.ts
src/core/core.bsq
src/core/xcore_string_exec.bsq
src/core/xcore_string_smt.bsq
test/cppoutput/cppemit_nf.ts
test/gc/gc_nf.ts

This sets up whats necessary for emitting our unicode and ascii char buffers to help us get setup for adding a rope backend to our strings.
I also modified our emission to also spit out the `cppruntime.cpp` file and added it to the cpp makefile since its a bit of a more pleasant location to keep all the char buffer ops.

Cpp Emission of Char Buffers

---

src/core/xcore_list_exec.bsq
src/core/xcore_map_exec.bsq

This fixes deletion from our RB trees (was detected in map deletion while running the cpp transformer) causing failures. From what I found our deletion was not doing proper rebalancing which caused a later call to `mink` to fail caused by a `BBLeaf` being passed in. I also added a extra case to `insert_helper` ensuring if a `BBLeaf` finds its way into this function we don't explode. And generally cleaned up some of the redundant deletion logic I wrote initially.

RB Deletion Fix

---

src/backend/cpp/cpprepr/body.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/core/xcore_list_exec.bsq

This adds support for `VariableMultiInitilizationExplicitStatement`, `VariableMultiInitilizationImplicitStatement`, and `ReturnMultiStatement` to the cpp emitter.
With these changes I was able to sucessfully compile `db.bsq` test (although I have not simulated a proper work load on it yet).
Multiple initilization ended up looking something like so, we declare all variables used then in a deeper scope assign to correct elist entry in rhs.
```
let y, z = (|1i, 2n|);
```
⬇️
```
[[maybe_unused]] __CoreCpp::Int y;
[[maybe_unused]] __CoreCpp::Nat z;
{
__CoreCpp::Tuple2<1, 1> elist = __CoreCpp::Tuple2<1, 1>(1_i, 2_n);
y = elist.access<__CoreCpp::Int, 0>();
z = elist.access<__CoreCpp::Nat, 1>();
}
```

Multiple Initialization and Return Multiple

---

src/backend/cpp/gc/src/runtime/common.h
src/backend/cpp/gc/src/runtime/memory/allocator.cpp
src/backend/cpp/gc/src/runtime/memory/allocator.h
src/backend/cpp/gc/src/runtime/memory/gc.cpp
src/backend/cpp/gc/src/runtime/memory/threadinfo.h
src/backend/cpp/gc/src/runtime/support/qsort.h
src/backend/cpp/gc/test/tree_basic/tree_basic.cpp
src/backend/cpp/gc/test/tree_wide/tree_wide.cpp
src/backend/cpp/runtime/cppruntime.hpp
test/gc/tree/tree_wide.test.js

- Fixed bug when forwarding pointers their new location was not properly reflected in parent
- Check for determining whether an object was eligible to be inserted on the freelist was way too complex, now we just check if its not allocated or a non root with a zero ref count 
- Ensured no weird type punning fiasco was happening in my quicksort, as we were initially passing a size_t as an int
- Better handling of the root points to root case
I did end up needing to zerofill pages in initialization to prevent left over garbage seeping its way into the collector. 
With these changes I was able to run nbody using `-O3` and canaries disabled for the typical 50,000,000 cycles in ~2 mins with an average collection time of ~0.27ms. This is without our packed 8 byte metadata (as I haven't gotten …

GC Fixes/Improvements

---

src/bsqir/simplifier/constsimplify.bsq
src/bsqir/simplifier/explicitify.bsq
src/frontend/bsqir_emit.ts

Adds necessary support for our compiler optimization pass benchmark to make it through const simplify and explicitify.

Op-Pass Benchmark Through Simplify & Explicitify

---

src/backend/cpp/runtime/cppruntime.cpp
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
src/core/xcore_crope_exec.bsq
src/core/xcore_list_exec.bsq
src/frontend/closed_terms.ts
test/cppoutput/mcall_exps/simple_resolved.test.js

Adds support for rope prepend and removing prefix rope. I also had to add support for testing whether a rope starts with another rope to get these to work and decided to rework a bit of how I structured our rope ops. They now use an iterator based approach where we generate the buffers present in order then walk to simplify comparison logic.

Rope Prepend and removePrefixString

---

src/backend/cpp/gc/src/runtime/common.h
src/backend/cpp/gc/src/runtime/memory/allocator.cpp
src/backend/cpp/gc/src/runtime/memory/allocator.h
src/backend/cpp/gc/src/runtime/memory/gc.cpp
src/backend/cpp/gc/src/runtime/memory/threadinfo.cpp
src/backend/cpp/gc/src/runtime/support/arraylist.h

- We ensure for an object to be forwarded it must be a non root young object 
- When computing dead roots, before putting a root that was dropped from the `old_roots` list onto our `pending_decs` list we ensure its ref count is 0 to handle the root points to root case
- Removed buggy logic in `processPage()` which created the possibility of a page on the `pendinggc_pages` list to be re-inserted onto the same list
- When moving the roots list over to the old roots list we ensure these objects `isyoung` flag is set to false
- Fixed page deletion bug in `tryRemoveFromFilledPages()` where if our page was first item in list we would just keep iterating instead of removing and returning
- If array list is only one page with one element and we try to `shift_front_slow()` or `shift_back_slow()` …

GC Bug Fixes

---

src/backend/cpp/transformer/cpptransform.bsq

This moves the type info generation logic outside of the transformer into its own namespace.

Move Type Info Generation

---

src/backend/cpp/cpprepr/cppassembly.bsq
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/backend/cpp/transformer/cpptransform.bsq
test/cppoutput/fcall_exps/ns_fcalls_prepost.test.js
test/cppoutput/map/map_access.test.js
test/cppoutput/map/map_delete.test.js

Closes #328.
Adds support for emission of pre conditions. I noticed post conditions aren't used anywhere currently so I decided to just lay out a skeleton for their support but no implementation.

Cpp Emit Pre Conditions

---

src/backend/cpp/runtime/cppruntime.cpp
src/backend/cpp/runtime/cppruntime.hpp
src/backend/cpp/transformer/cppemitter.bsq
src/core/xcore_crope_exec.bsq
src/frontend/closed_terms.ts
test/cppoutput/cstring/cstring_startends.test.js

Adds support for rope iteration done in C++. For now I converted `startsWithString()` to use our C++ rope iterators - so there are still quite a few functions left to convert.
Also fixed a bug in append that prevented our ropes from rebalancing!

Rope Iterator

---

src/core/xcore_crope_exec.bsq

Closes #326.
This finishes up removing all the nonsense I had originally used to write the ropes (like putting all buffers of a rope into a list then iterating through that, ouch), now all functions (that are implemented) use the C++ iterator so we should be running better.

More CRope Improvements

---

src/backend/cpp/runtime/cppruntime.cpp
src/backend/cpp/runtime/cppruntime.hpp
src/core/xcore_crope_exec.bsq

Discovered a bug with the rope iterators, I forgot about small strings (one buffer) always being stack allocated, so I was previously storing stale stack references! This popped up with higher optimization levels on, as the optimizer was freely moving around the stack allocated buffers I stored a reference to. We now have a special case for only one buffer being present where we do an inexpensive copy.

Rope Iterator Inline String Bug Fix
